### PR TITLE
add parens around section prefixes (just use CSS)

### PR DESCRIPTION
**Pull request by kcivey**
Add parentheses around the section prefixes, as requested by @vzvenyach.

### CODE REVIEW

**Comment by waldoj** [comment]
FWIW, these parentheses aren't just style—they're important, meaningful data. If CSS is the easiest way to add them, I get it, but they should really be present in the actual rendered text, regardless of CSS.

**Comment by tmcw** [comment]
@kcivey added you as an owner to the openlawdc org, so you can merge it at your leisure! Your pick whether this should be CSS or on-page content.

**Comment by waldoj** [comment]
(Don't let the perfect be the enemy of the good, my comment notwithstanding.)

**Comment by waldoj** [comment]
And, yes, I'm participating in two hackathons at the same time.

**Comment by kcivey** [comment]
Thanks, Tom!

Waldo, do you have any input on the issue of telling whether "i" is a lowercase letter or a lowercase roman numeral? I guess it's not that hard. We just need to rewrite things so that the function determining the hierarchy level has some context (it at least needs to know the previous prefix).

**Comment by kcivey** [comment]
@waldoj, are there cases where having or not having parens makes a difference? @vzvenyach says every level has parens. Maybe that's specific to DC?

**Comment by waldoj** [comment]
> Waldo, do you have any input on the issue of telling whether "i" is a lowercase letter or a lowercase roman numeral? I guess it's not that hard. We just need to rewrite things so that the function determining the hierarchy level has some context (it at least needs to know the previous prefix).

I do. [That's handled in 99% of cases right now](https://github.com/statedecoded/subsection-identifier/blob/master/subsection-identifier.php#L95), and [I'm working on a further solution](https://github.com/statedecoded/statedecoded/issues/238#issuecomment-18618306), which is to parse statefully, so that "i" is assumed to be a letter if it follows "h," but presumed to be a Roman numeral if it does not.

> are there cases where having or not having parens makes a difference?

Yes, there are cases like that. Is it section A12ab: is that section (A)(1)(2)(a)(b), (A)(12)(ab), or some other combination thereof? But even if we ignore that, and Washington puts parens around every subsection identifier, the DC Code doesn't exist in a bubble—this is not a universal practice, many people may reasonably assume that parentheses mere decoration, rather than an fundamental part of the identifier.

**Comment by kcivey** [comment]
I was assuming that internally the parts of the hierarchy are separate, so the question is whether ['A', '1', 'b'] would be different from ['(A)', '(1)', '(b)'].

But ultimately we need to decide how much more work it makes sense to put into this DC Code browser, which is really a dead end, rather than working on getting things into State Decoded.

**Comment by waldoj** [comment]
Those parts aren't different when rendered as (for instance) anchors. `#(1)(a)(b)` and `#(1)(ab)` are different. (Most legal codes, when they get past "z," start again with "aa," "ab," "abc," etc. I don't know whether D.C. does that, but it's a fair bet, since there's not really a better thing to do at that point. :))

**Comment by kcivey** [comment]
I added something to look at the previous prefix to distinguish the "i" cases in e327d3157fc510e3dfb651659fe70ca49b74d457.

**Pull request merged**
